spring.application.name=demo1
groq.api.key=f9f70acccbmshc29c412896592dbp187692jsn3256b5d7d1c3
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.datasource.url=jdbc:mysql://localhost:3306/Major
spring.datasource.username=root
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true